model = "PrimeIntellect/INTELLECT-3"
max_steps = 500
batch_size = 512
rollouts_per_example = 16
# With batch_size == rollouts_per_example, you get 1 prompt (example) per step.

[sampling]
max_tokens = 10000

[[env]]
id = "13point5/tldraw"

[val]
num_examples = 64
rollouts_per_example = 1
interval = 10

[wandb]
project = "tldraw"
name = "intellect-3-tldraw"
entity = "13point5-labs"